version: 2.1

orbs:
  docker: circleci/docker@2.1.2

jobs:
  run-lint:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "app/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            chmod -R +x ./bin/
            python3 -m venv .devops-capstone
            source .devops-capstone/bin/activate
            make install
      - save_cache:
          paths:
            - ./.devops-capstone
          key: v1-dependencies-{{ checksum "app/requirements.txt" }}
      - run:
          name: Run lint
          command: |
            source .devops-capstone/bin/activate
            make lint

  build-and-push-docker-image:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build & push docker image
          command: |
            export VERSION=$(<app/version.txt)
            
            # Build docker image
            docker build -t flask-app app
            
            # Tag image
            docker tag flask-app nhothuy48cb/flask-app:${VERSION}
            docker tag flask-app nhothuy48cb/flask-app:lastest
            
            # Login to docker-hub
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            
            # We publish two images with different version tags: 
            # - numbered version
            # - "latest"
            docker push nhothuy48cb/flask-app:${VERSION}
            docker push nhothuy48cb/flask-app:lastest

workflows:
  default:
    jobs:
      - run-lint
      - build-and-push-docker-image:
          requires: [run-lint]