version: 2.1

orbs:
  docker: circleci/docker@2.1.2

jobs:
  run-lint:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "app/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            chmod -R +x ./bin/
            python3 -m venv .devops-capstone
            source .devops-capstone/bin/activate
            make install
      - save_cache:
          paths:
            - ./.devops-capstone
          key: v1-dependencies-{{ checksum "app/requirements.txt" }}
      - run:
          name: Run lint
          command: |
            source .devops-capstone/bin/activate
            make lint

  build-and-push-docker-image:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build and push docker image
          command: |
            export VERSION=$(<app/version.txt)
            
            # Build docker image
            docker build -t flask-app app
            
            # Tag image
            docker tag flask-app nhothuy48cb/flask-app:${VERSION}
            docker tag flask-app nhothuy48cb/flask-app:lastest
            
            # Login to docker-hub
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            
            # We publish two images with different version tags: 
            # - numbered version
            # - "latest"
            docker push nhothuy48cb/flask-app:${VERSION}
            docker push nhothuy48cb/flask-app:lastest

  deploy-green:
    docker:
      - image: cimg/python:3.7.13
    steps:
      - checkout
      - run:
          name: Install awscli and gettext-base
          command: |
            sudo apt update
            sudo apt-get install awscli
            sudo apt-get install gettext-base
      - run:
          name: Install aws-iam-authenticator
          command: |
            curl -o aws-iam-authenticator curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/aws-iam-authenticator
            chmod +x ./aws-iam-authenticator
            sudo mv ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator
      - run:
          name: Install kubectl
          command: |
            curl -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: Connect to cluster
          command: |
            aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $CLUSTER_NAME
      - run:
          name: Deploy
          command: |
            kubectl apply -f k8s/deployment.yaml
            kubectl apply -f k8s/test-service.yaml
            kubectl get all

  wait-manual-approval:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - run: printf "A hold job to wait for a manual approval"

  deploy-blue:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - run: printf "Approved"

workflows:
  default:
    jobs:
      - deploy-green
      - wait-manual-approval:
          type: approval
          requires: [deploy-green]
      - deploy-blue:
          requires: [wait-manual-approval]
      #- run-lint
      #- build-and-push-docker-image:
          #requires: [run-lint]
      #- deploy:
          #requires: [build-and-push-docker-image]