apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: flask-app
    version: 1-0
  type: LoadBalancer